# Lab | Web Scraping

## Introduction

Web scraping can be defined as "the construction of an agent to download, parse, and organize data from the web in an automated manner". In this lab, you will practice a series of exercises to practice your web scraping skills.  

Each exercise is independent from the previous one. If you get stuck in one exercise you can skip to the next one.

### Hints:
- Check the response status code for each request to ensure you have obtained the intended content.
- Print the response text in each request to understand the kind of info you are getting and its format.

### Documentation:
- [Requests library](http://docs.python-requests.org/en/master/#the-user-guide)
- [Beautiful Soup Doc](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Scrapy](https://scrapy.org/)
- [List of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
- [HTML basics](http://www.simplehtmlguide.com/cheatsheet.php)
- [CSS basics](https://www.cssbasics.com/#page_start)

## Libraries
- Make sure you have all libraries installed before start the lab.  
- In this lab you will use `requests`, `BeautifulSoup` and `pandas`.

In [1]:
# Import the libraries here

import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

## Scraping github trending developers
- In this first exercise we will scraping the github trending developers. Use the url below.
```python
url = 'https://github.com/trending/developers'
```

In [2]:
# Your code here

url = 'https://github.com/trending/developers'

- Start using `requests.get()` over the 'url', save your output in a new variable called `get_html`
- The output should be `<Response [200]>`

In [3]:
# Your code here

get_html = requests.get(url)
get_html

- Explore the request methods
- Try get_html.status_code and get_html.encoding

In [4]:
# Your code here

get_html.status_code

200

In [5]:
get_html.encoding

'utf-8'

- Call the `get_html.content` method to return the page content.
- Save in a variable called `html_content`

In [6]:
# Your code here

html_content = get_html.content

- Use the BeautifulSoup to parse your result. You can use the code below.
```python
soup = BeautifulSoup(html_content, "lxml")
```

In [7]:
# Your code here

soup = BeautifulSoup(html_content, "lxml")

### Display the names of the trending developers retrieved in the previous step.

- Find out the html tag and class names used for the developer names.
- Use BeautifulSoup to extract all the html elements that contain the developer names.
- Use string manipulation techniques to replace whitespaces and line breaks (i.e. \n) in the *text* of each html element. Use a list to store the clean names.

Your output should look like below:

```
['KentC.Dodds',
 'SethVargo',
 'VadimDemedes',
 'PaulBeusterien',
 'DanImhoff',
 'CalebPorzio',
 'TannerLinsley',
 'InesMontani',
 'Mr.doob',
 'JacobHoffman-Andrews',
 'TianonGravi',
 'TaylorOtwell',
 'MatthewJohnson',
 'MathiasBuus',
 'TimHolman',
 'AlonZakai',
 'HadleyWickham',
 'Bo-YiWu',
 'TobiasKoppers',
 'KentaroWada',
 'TeppeiFukuda',
 'MartinAtkins',
 'RyanMcKinley',
 'KlausPost',
 'JamesAgnew']
 ```

In [8]:
# Your code here

names = soup.find_all('h1', {'class': 'h3 lh-condensed'})
names[0]

<h1 class="h3 lh-condensed">
<a data-hydro-click='{"event_type":"explore.click","payload":{"click_context":"TRENDING_DEVELOPERS_PAGE","click_target":"OWNER","click_visual_representation":"TRENDING_DEVELOPER","actor_id":null,"record_id":8855632,"originating_url":"https://github.com/trending/developers","user_id":null}}' data-hydro-click-hmac="b20e3c47b28ecca9b9fddabf3f86288110cb6679d50a39e38781b3892c68cc4b" data-view-component="true" href="/felangel">
            Felix Angelov
</a> </h1>

In [9]:
names[0].text

'\n\n            Felix Angelov\n '

In [10]:
trending_dev_list = [name.text.strip() for name in names]
trending_dev_list

['Felix Angelov',
 'Lee Robinson',
 'Matthias Fey',
 'Sebastián Ramírez',
 'Brad Fitzpatrick',
 'Alex Goodman',
 'Stefan Prodan',
 'Daishi Kato',
 'Shivam Mathur',
 'Christophe Coevoet',
 'Jonah Lawrence',
 'Arda TANRIKULU',
 'Bee',
 'Pedro Piñera Buendía',
 'Alice Ryhl',
 'Javier Suárez',
 'Olivier Halligon',
 'Rick Waldron',
 'Henrik Rydgård',
 'Samuel Colvin',
 'Barry vd. Heuvel',
 'Hajime Hoshi',
 'Kirk Byers',
 'David Tolnay',
 'Teppei Fukuda']

In [11]:
trending_dev = pd.DataFrame(trending_dev_list)
trending_dev.columns = ['Trending Developer']
trending_dev

      Trending Developer
0          Felix Angelov
1           Lee Robinson
2           Matthias Fey
3      Sebastián Ramírez
4       Brad Fitzpatrick
5           Alex Goodman
6          Stefan Prodan
7            Daishi Kato
8          Shivam Mathur
9     Christophe Coevoet
10        Jonah Lawrence
11        Arda TANRIKULU
12                   Bee
13  Pedro Piñera Buendía
14            Alice Ryhl
15         Javier Suárez
16      Olivier Halligon
17          Rick Waldron
18        Henrik Rydgård
19         Samuel Colvin
20      Barry vd. Heuvel
21          Hajime Hoshi
22            Kirk Byers
23          David Tolnay
24         Teppei Fukuda

In [12]:
# Option 2

# dev_list = [i.text.strip().replace(' ','').replace('\n\n', ' ') for i in soup.find_all('h1', {'class': 'h3 lh-condensed'})]
# dev_list

## Scraping function
- Now you have learned how to use Requests and BeautifulSoup. 
- Create the function below to make your scraping easier.
```python
def url_bs4(url):
    get_html = requests.get(url)
    print(get_html.status_code)
    print(get_html.encoding)
    html = get_html.content
    soup = BeautifulSoup(html)
    return soup
```

In [13]:
# Your code here

def url_bs4(url):
  get_html = requests.get(url)
  print(get_html.status_code)
  print(get_html.encoding)
  html = get_html.content
  soup = BeautifulSoup(html)
  return soup

## Scraping Walt Disney wikipedia page
- Use the url below to scraping the Walt Disney Wikipedia page.
- Use the url_bs4 function and check the status.
```python
url_disney = 'https://en.wikipedia.org/wiki/Walt_Disney'
```

In [14]:
# Your code here

url_disney = 'https://en.wikipedia.org/wiki/Walt_Disney'
soup_disney = url_bs4(url_disney)

200
UTF-8

- Create a list with  all the image links from Walt Disney Wikipedia page
- Try the `.find_all` method to find the images

In [15]:
# Your code here

soup.find_all('img')

[<img alt="" aria-label="Team" class="avatar mr-2 flex-shrink-0 js-jump-to-suggestion-avatar d-none" height="28" src="" width="28"/>,
 <img alt="" aria-label="Team" class="avatar mr-2 flex-shrink-0 js-jump-to-suggestion-avatar d-none" height="28" src="" width="28"/>,
 <img alt="" aria-label="Team" class="avatar mr-2 flex-shrink-0 js-jump-to-suggestion-avatar d-none" height="28" src="" width="28"/>,
 <img alt="" aria-label="Team" class="avatar mr-2 flex-shrink-0 js-jump-to-suggestion-avatar d-none" height="28" src="" width="28"/>,
 <img alt="@felangel" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/8855632?s=96&amp;v=4" width="48"/>,
 <img alt="@leerob" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/9113740?s=96&amp;v=4" width="48"/>,
 <img alt="@rusty1s" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/6945922?s=96&amp;v=4" width="48"/>,
 <img alt="@tiangolo" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/1326112?s=96&amp;v=4" width="48"/>,
 <img alt="@bradfitz" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/2621?s=96&amp;v=4" width="48"/>,
 <img alt="@wagoodman" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/590471?s=96&amp;v=4" width="48"/>,
 <img alt="@stefanprodan" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/3797675?s=96&amp;v=4" width="48"/>,
 <img alt="@dai-shi" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/490574?s=96&amp;v=4" width="48"/>,
 <img alt="@shivammathur" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/1571086?s=96&amp;v=4" width="48"/>,
 <img alt="@stof" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/439401?s=96&amp;v=4" width="48"/>,
 <img alt="@DenverCoder1" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/20955511?s=96&amp;v=4" width="48"/>,
 <img alt="@ardatan" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/20847995?s=96&amp;v=4" width="48"/>,
 <img alt="@bee-san" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/10378052?s=96&amp;v=4" width="48"/>,
 <img alt="@pepibumur" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/663605?s=96&amp;v=4" width="48"/>,
 <img alt="@Darksonn" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/928074?s=96&amp;v=4" width="48"/>,
 <img alt="@jsuarezruiz" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/6755973?s=96&amp;v=4" width="48"/>,
 <img alt="@AliSoftware" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/216089?s=96&amp;v=4" width="48"/>,
 <img alt="@rwaldron" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/27985?s=96&amp;v=4" width="48"/>,
 <img alt="@hrydgard" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/130929?s=96&amp;v=4" width="48"/>,
 <img alt="@samuelcolvin" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/4039449?s=96&amp;v=4" width="48"/>,
 <img alt="@barryvdh" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/973269?s=96&amp;v=4" width="48"/>,
 <img alt="@hajimehoshi" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/16950?s=96&amp;v=4" width="48"/>,
 <img alt="@ktbyers" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/899716?s=96&amp;v=4" width="48"/>,
 <img alt="@dtolnay" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/1940490?s=96&amp;v=4" width="48"/>,
 <img alt="@knqyf263" class="rounded avatar-user" height="48" src="https://avatars.githubusercontent.com/u/2253692?s=96&amp;v=4" width="48"/>]

In [16]:
[i.get('src').strip('//') for i in soup_disney.find_all('img')]

['upload.wikimedia.org/wikipedia/en/thumb/e/e7/Cscr-featured.svg/20px-Cscr-featured.svg.png',
 'upload.wikimedia.org/wikipedia/en/thumb/8/8c/Extended-protection-shackle.svg/20px-Extended-protection-shackle.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/d/df/Walt_Disney_1946.JPG/220px-Walt_Disney_1946.JPG',
 'upload.wikimedia.org/wikipedia/commons/thumb/8/87/Walt_Disney_1942_signature.svg/128px-Walt_Disney_1942_signature.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Walt_Disney_envelope_ca._1921.jpg/220px-Walt_Disney_envelope_ca._1921.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Newman_Laugh-O-Gram_%281921%29.webm/220px-seek%3D2-Newman_Laugh-O-Gram_%281921%29.webm.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Trolley_Troubles_poster.jpg/170px-Trolley_Troubles_poster.jpg',
 'upload.wikimedia.org/wikipedia/en/thumb/4/4e/Steamboat-willie.jpg/170px-Steamboat-willie.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/5/57/Walt_Disney_1935.jpg/170px-Walt_Disney_1935.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg/220px-Walt_Disney_Snow_white_1937_trailer_screenshot_%2813%29.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/1/15/Disney_drawing_goofy.jpg/170px-Disney_drawing_goofy.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/1/13/DisneySchiphol1951.jpg/220px-DisneySchiphol1951.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/8/8c/WaltDisneyplansDisneylandDec1954.jpg/220px-WaltDisneyplansDisneylandDec1954.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Walt_disney_portrait_right.jpg/170px-Walt_disney_portrait_right.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Walt_Disney_Grave.JPG/170px-Walt_Disney_Grave.JPG',
 'upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Roy_O._Disney_with_Company_at_Press_Conference.jpg/170px-Roy_O._Disney_with_Company_at_Press_Conference.jpg',
 'upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Disney_Display_Case.JPG/170px-Disney_Display_Case.JPG',
 'upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Disney1968.jpg/170px-Disney1968.jpg',
 'upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/10px-OOjs_UI_icon_edit-ltr-progressive.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Disneyland_Resort_logo.svg/135px-Disneyland_Resort_logo.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/d/da/Animation_disc.svg/30px-Animation_disc.svg.png',
 'upload.wikimedia.org/wikipedia/en/thumb/6/69/P_vip.svg/29px-P_vip.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Magic_Kingdom_castle.jpg/24px-Magic_Kingdom_castle.jpg',
 'upload.wikimedia.org/wikipedia/en/thumb/e/e7/Video-x-generic.svg/30px-Video-x-generic.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Flag_of_Los_Angeles_County%2C_California.svg/30px-Flag_of_Los_Angeles_County%2C_California.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Blank_television_set.svg/30px-Blank_television_set.svg.png',
 'upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/30px-Flag_of_the_United_States.svg.png',
 'upload.wikimedia.org/wikipedia/en/thumb/4/4a/Commons-logo.svg/22px-Commons-logo.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Wikiquote-logo.svg/25px-Wikiquote-logo.svg.png',
 'upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wikidata-logo.svg/30px-Wikidata-logo.svg.png',
 'upload.wikimedia.org/wikipedia/en/thumb/8/8a/OOjs_UI_icon_edit-ltr-progressive.svg/10px-OOjs_UI_icon_edit-ltr-progressive.svg.png',
 'en.wikipedia.org/wiki/Special:CentralAutoLogin/start?type=1x1',
 'static/images/footer/wikimedia-button.png',
 'static/images/footer/poweredby_mediawiki_88x31.png']

## Scraping earthquakes
- Use the url below to scraping the 50 latest earthquakes.
```python
url_eq='https://www.emsc-csem.org/Earthquake/'
```
- Instead  of use requests and BeautifulSoup,  try the function `pd.read_html(url_eq)`
- You will notice that it returns a list of elements. One of the elements in this list is the earthquake table
- You will need to clean the columns names, the Date & Time values,  and drop the last 3 rows

In [17]:
# Your code here

url_eq = 'https://www.emsc-csem.org/Earthquake/'
df_table = pd.read_html(url_eq)
df_table

[    0                                                  1  \
 0 NaN  set_server_date(2021,10,7,18,42,9)  Current ti...

                          2
 0  Member access  Name Pwd  ,
                0              1
 0  Member access  Member access
 1            NaN            NaN
 2           Name            NaN
 3            NaN            NaN
 4            Pwd            NaN
 5            NaN            NaN
 6            NaN            NaN,
                                                    0         1
 0  - Sorting by column is performed on the data o...  Glossary,
    CitizenResponse                                  \
      12345678910» 12345678910».1 12345678910».2
 0              NaN             NaN             NaN
 1               66             NaN              IV
 2              NaN             NaN             NaN
 3                1             NaN             III
 4              NaN             NaN             NaN
 5              NaN             NaN             NaN
 6              NaN             NaN             NaN
 7              NaN             NaN             NaN
 8              NaN             NaN             NaN
 9              NaN             NaN             NaN
 10             NaN             NaN             NaN
 11               1             NaN               F
 12             NaN             NaN             NaN
 13             NaN             NaN             NaN
 14             NaN             NaN             NaN
 15             NaN             NaN             NaN
 16             NaN             NaN             NaN
 17             NaN             NaN             NaN
 18             NaN             NaN             NaN
 19             NaN             NaN             NaN
 20             NaN             NaN             NaN
 21             NaN             NaN             NaN
 22             NaN             NaN             NaN
 23             NaN             NaN             NaN
 24             NaN             NaN             NaN
 25             NaN             NaN             NaN
 26             NaN             NaN             NaN
 27             NaN             NaN             NaN
 28             NaN             NaN             NaN
 29             NaN             NaN             NaN
 30             NaN             NaN             NaN
 31             NaN             NaN             NaN
 32             NaN             NaN             NaN
 33             NaN             NaN             NaN
 34             NaN             NaN             NaN
 35             NaN             NaN             NaN
 36             NaN             NaN             NaN
 37             NaN             NaN             NaN
 38             NaN             NaN             NaN
 39             NaN             NaN             NaN
 40             NaN             NaN             NaN
 41             NaN             NaN             NaN
 42             NaN             NaN             NaN
 43             NaN             NaN             NaN
 44              59             NaN               V
 45             NaN             NaN             NaN
 46             NaN             NaN             NaN
 47             NaN             NaN             NaN
 48             NaN             NaN             NaN
 49             NaN             NaN             NaN
 50             NaN             NaN             NaN
 51   12345678910»   12345678910»   12345678910»
 52             NaN             NaN             NaN

                        Date & Time UTC Latitude degrees                  \
                          12345678910»    12345678910» 12345678910».1
 0       2021-10-07 18:36:07.106min ago            37.00               N
 1       2021-10-07 18:28:03.814min ago            22.36               N
 2       2021-10-07 18:24:31.417min ago            28.56               N
 3       2021-10-07 18:14:53.727min ago            13.86               N
 4       2021-10-07 17:56:14.645min ago            55.70               S
 5       2021-10-07 17:55:09.146min ago            28.38               N
 6       2021-10-07 17:53:23.248min ago            16.90               N
 7       2021-10-07 17:45:21.056min ago             7.92               S
 8       2021-10-07 17:43:01.059min ago             6.47               S
 9   2021-10-07 17:24:24.71hr 17min ago            39.53               N
 10  2021-10-07 17:21:50.01hr 20min ago            28.56               N
 11  2021-10-07 17:17:46.51hr 24min ago            44.20               N
 12  2021-10-07 17:14:38.61hr 27min ago            28.56               N
 13  2021-10-07 17:02:39.01hr 39min ago             2.76               S
 14  2021-10-07 16:59:48.31hr 42min ago            35.19               N
 15  2021-10-07 16:52:59.81hr 49min ago            28.56               N
 16  2021-10-07 16:47:20.51hr 54min ago            28.56               N
 17  2021-10-07 16:44:22.11hr 57min ago            31.84               N
 18  2021-10-07 16:32:21.02hr 09min ago            10.98               N
 19  2021-10-07 16:25:17.12hr 16min ago            19.24               N
 20  2021-10-07 16:24:06.02hr 18min ago            45.88               S
 21  2021-10-07 16:19:28.62hr 22min ago            28.57               N
 22  2021-10-07 16:13:42.72hr 28min ago            28.56               N
 23  2021-10-07 16:11:43.62hr 30min ago            12.67               N
 24  2021-10-07 15:52:54.32hr 49min ago            28.56               N
 25  2021-10-07 15:49:15.42hr 52min ago            28.58               N
 26  2021-10-07 15:38:14.53hr 03min ago            37.55               N
 27  2021-10-07 15:25:04.23hr 17min ago            37.69               N
 28  2021-10-07 15:24:38.03hr 17min ago            31.58               N
 29  2021-10-07 15:23:14.03hr 18min ago            28.57               N
 30  2021-10-07 15:07:25.03hr 34min ago            19.84               S
 31  2021-10-07 14:54:14.33hr 47min ago            37.39               N
 32  2021-10-07 14:51:46.23hr 50min ago            19.14               N
 33  2021-10-07 14:49:38.23hr 52min ago            19.16               N
 34  2021-10-07 14:37:30.04hr 04min ago            10.67               N
 35  2021-10-07 14:26:04.74hr 16min ago            28.58               N
 36  2021-10-07 14:24:30.04hr 17min ago            41.30               N
 37  2021-10-07 14:12:20.64hr 29min ago            40.44               N
 38  2021-10-07 14:10:47.04hr 31min ago            20.87               S
 39  2021-10-07 14:02:47.34hr 39min ago            32.72               N
 40  2021-10-07 14:02:09.14hr 39min ago            39.02               N
 41  2021-10-07 13:52:50.64hr 49min ago            38.84               S
 42  2021-10-07 13:47:00.14hr 55min ago            62.39               N
 43  2021-10-07 13:44:12.04hr 57min ago             5.08               N
 44  2021-10-07 13:41:24.25hr 00min ago            35.52               N
 45  2021-10-07 13:24:32.95hr 17min ago            28.55               N
 46  2021-10-07 13:18:26.35hr 23min ago            28.56               N
 47  2021-10-07 13:16:23.55hr 25min ago            44.28               N
 48  2021-10-07 13:14:20.85hr 27min ago            28.57               N
 49  2021-10-07 13:13:38.65hr 28min ago            33.58               S
 50                                 NaN              NaN             NaN
 51                       12345678910»    12345678910»   12345678910»
 52                                 NaN              NaN             NaN

    Longitude degrees                       Depth km        Mag [+]  \
        12345678910» 12345678910».1  12345678910»  12345678910»
 0             118.33               W              1             Md
 1              94.81               E            107             mb
 2              17.84               W             12             ML
 3             120.79               E            158             Mw
 4              26.39               W             10             mb
 5              16.10               W             16             ML
 6              60.29               W              2             ML
 7             106.89               E             10              M
 8             130.21               E            151              M
 9              26.21               E              7             ML
 10             17.85               W             11             ML
 11             12.22               E             10             ML
 12             17.82               W             14             ML
 13            129.59               E             10              M
 14             25.30               E              8             ML
 15             17.84               W             10             ML
 16             17.85               W             13             ML
 17            137.93               E            378             mb
 18             86.33               W             26              M
 19            155.50               W             35             ML
 20             72.93               W              7              M
 21             17.84               W             14             ML
 22             17.85               W             13             ML
 23             88.35               W             43             mb
 24             17.84               W             12             ML
 25             17.84               W             10             ML
 26             44.73               E              6             ML
 27             30.15               E              5             ML
 28            104.55               W              5             ML
 29             17.83               W             10             ML
 30             71.08               W             29              M
 31            117.11               W              0             ml
 32            155.38               W             30             Ml
 33            155.48               W             32             Ml
 34             86.58               W             13              M
 35             17.83               W             37             ML
 36            142.20               E             60              M
 37             51.78               E             62             ML
 38             69.10               W            111              M
 39            100.70               W              7             ML
 40             27.86               E              7             ML
 41            175.18               E            331              M
 42            150.61               W             68             ML
 43            126.15               E             32              M
 44            140.07               E             60             Mw
 45             17.85               W             14             ML
 46             17.83               W             11             ML
 47             92.67               E              2             mb
 48             17.83               W             11             ML
 49            138.68               E              2             ML
 50               NaN             NaN            NaN            NaN
 51     12345678910»   12345678910»  12345678910»  12345678910»
 52               NaN             NaN            NaN            NaN

    Region name [+]                   Last update [-] Unnamed: 12_level_0
      12345678910»                     12345678910»       12345678910»
 0              2.3                CENTRAL CALIFORNIA    2021-10-07 18:37
 1              5.6                           MYANMAR    2021-10-07 18:40
 2              2.7      CANARY ISLANDS, SPAIN REGION    2021-10-07 18:29
 3              5.2              MINDORO, PHILIPPINES    2021-10-07 18:40
 4              5.5     SOUTH SANDWICH ISLANDS REGION    2021-10-07 18:38
 5              1.9      CANARY ISLANDS, SPAIN REGION    2021-10-07 18:03
 6              4.4   GUADELOUPE REGION, LEEWARD ISL.    2021-10-07 18:15
 7              2.5                   JAVA, INDONESIA    2021-10-07 18:10
 8              4.5                         BANDA SEA    2021-10-07 17:50
 9              2.1  NEAR THE COAST OF WESTERN TURKEY    2021-10-07 17:39
 10             2.5      CANARY ISLANDS, SPAIN REGION    2021-10-07 17:34
 11             2.7                    NORTHERN ITALY    2021-10-07 17:54
 12             3.5      CANARY ISLANDS, SPAIN REGION    2021-10-07 17:34
 13             3.0                  SERAM, INDONESIA    2021-10-07 17:35
 14             3.0                     CRETE, GREECE    2021-10-07 17:02
 15             3.4      CANARY ISLANDS, SPAIN REGION    2021-10-07 17:06
 16             2.6      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:58
 17             4.1         IZU ISLANDS, JAPAN REGION    2021-10-07 17:44
 18             2.9           OFF COAST OF COSTA RICA    2021-10-07 16:36
 19             2.8          ISLAND OF HAWAII, HAWAII    2021-10-07 16:35
 20             2.5                      AISEN, CHILE    2021-10-07 16:36
 21             2.7      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:47
 22             2.9      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:46
 23             4.0              OFFSHORE EL SALVADOR    2021-10-07 16:49
 24             3.1      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:01
 25             3.6      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:40
 26             2.7    TURKEY-IRAN-IRAQ BORDER REGION    2021-10-07 16:00
 27             2.5                    WESTERN TURKEY    2021-10-07 15:44
 28             2.5                     WESTERN TEXAS    2021-10-07 17:19
 29             2.7      CANARY ISLANDS, SPAIN REGION    2021-10-07 15:41
 30             2.7      OFF COAST OF TARAPACA, CHILE    2021-10-07 15:24
 31             2.3                            NEVADA    2021-10-07 16:09
 32             2.1          ISLAND OF HAWAII, HAWAII    2021-10-07 14:57
 33             2.4          ISLAND OF HAWAII, HAWAII    2021-10-07 14:55
 34             4.5           OFF COAST OF COSTA RICA    2021-10-07 15:21
 35             3.8      CANARY ISLANDS, SPAIN REGION    2021-10-07 15:08
 36             4.1            HOKKAIDO, JAPAN REGION    2021-10-07 14:35
 37             3.2  CASPIAN SEA, OFFSHR TURKMENISTAN    2021-10-07 15:32
 38             2.8                   TARAPACA, CHILE    2021-10-07 14:52
 39             2.2                     WESTERN TEXAS    2021-10-07 18:36
 40             2.1                    WESTERN TURKEY    2021-10-07 14:26
 41             3.1       NORTH ISLAND OF NEW ZEALAND    2021-10-07 14:00
 42             3.2                    CENTRAL ALASKA    2021-10-07 16:25
 43             3.2             MINDANAO, PHILIPPINES    2021-10-07 13:56
 44             5.9  NEAR EAST COAST OF HONSHU, JAPAN    2021-10-07 14:53
 45             3.2      CANARY ISLANDS, SPAIN REGION    2021-10-07 13:30
 46             2.8      CANARY ISLANDS, SPAIN REGION    2021-10-07 13:35
 47             4.6          NORTHERN XINJIANG, CHINA    2021-10-07 16:06
 48             2.7      CANARY ISLANDS, SPAIN REGION    2021-10-07 13:36
 49             2.1     NEAR COAST OF SOUTH AUSTRALIA    2021-10-07 14:08
 50             NaN                               NaN                 NaN
 51   12345678910»                     12345678910»       12345678910»
 52             NaN                               NaN                 NaN  ]

In [18]:
df_eq = df_table[3]
df_eq

   CitizenResponse                                  \
     12345678910» 12345678910».1 12345678910».2
0              NaN             NaN             NaN
1               66             NaN              IV
2              NaN             NaN             NaN
3                1             NaN             III
4              NaN             NaN             NaN
5              NaN             NaN             NaN
6              NaN             NaN             NaN
7              NaN             NaN             NaN
8              NaN             NaN             NaN
9              NaN             NaN             NaN
10             NaN             NaN             NaN
11               1             NaN               F
12             NaN             NaN             NaN
13             NaN             NaN             NaN
14             NaN             NaN             NaN
15             NaN             NaN             NaN
16             NaN             NaN             NaN
17             NaN             NaN             NaN
18             NaN             NaN             NaN
19             NaN             NaN             NaN
20             NaN             NaN             NaN
21             NaN             NaN             NaN
22             NaN             NaN             NaN
23             NaN             NaN             NaN
24             NaN             NaN             NaN
25             NaN             NaN             NaN
26             NaN             NaN             NaN
27             NaN             NaN             NaN
28             NaN             NaN             NaN
29             NaN             NaN             NaN
30             NaN             NaN             NaN
31             NaN             NaN             NaN
32             NaN             NaN             NaN
33             NaN             NaN             NaN
34             NaN             NaN             NaN
35             NaN             NaN             NaN
36             NaN             NaN             NaN
37             NaN             NaN             NaN
38             NaN             NaN             NaN
39             NaN             NaN             NaN
40             NaN             NaN             NaN
41             NaN             NaN             NaN
42             NaN             NaN             NaN
43             NaN             NaN             NaN
44              59             NaN               V
45             NaN             NaN             NaN
46             NaN             NaN             NaN
47             NaN             NaN             NaN
48             NaN             NaN             NaN
49             NaN             NaN             NaN
50             NaN             NaN             NaN
51   12345678910»   12345678910»   12345678910»
52             NaN             NaN             NaN

                       Date & Time UTC Latitude degrees                  \
                         12345678910»    12345678910» 12345678910».1
0       2021-10-07 18:36:07.106min ago            37.00               N
1       2021-10-07 18:28:03.814min ago            22.36               N
2       2021-10-07 18:24:31.417min ago            28.56               N
3       2021-10-07 18:14:53.727min ago            13.86               N
4       2021-10-07 17:56:14.645min ago            55.70               S
5       2021-10-07 17:55:09.146min ago            28.38               N
6       2021-10-07 17:53:23.248min ago            16.90               N
7       2021-10-07 17:45:21.056min ago             7.92               S
8       2021-10-07 17:43:01.059min ago             6.47               S
9   2021-10-07 17:24:24.71hr 17min ago            39.53               N
10  2021-10-07 17:21:50.01hr 20min ago            28.56               N
11  2021-10-07 17:17:46.51hr 24min ago            44.20               N
12  2021-10-07 17:14:38.61hr 27min ago            28.56               N
13  2021-10-07 17:02:39.01hr 39min ago             2.76               S
14  2021-10-07 16:59:48.31hr 42min ago            35.19               N
15  2021-10-07 16:52:59.81hr 49min ago            28.56               N
16  2021-10-07 16:47:20.51hr 54min ago            28.56               N
17  2021-10-07 16:44:22.11hr 57min ago            31.84               N
18  2021-10-07 16:32:21.02hr 09min ago            10.98               N
19  2021-10-07 16:25:17.12hr 16min ago            19.24               N
20  2021-10-07 16:24:06.02hr 18min ago            45.88               S
21  2021-10-07 16:19:28.62hr 22min ago            28.57               N
22  2021-10-07 16:13:42.72hr 28min ago            28.56               N
23  2021-10-07 16:11:43.62hr 30min ago            12.67               N
24  2021-10-07 15:52:54.32hr 49min ago            28.56               N
25  2021-10-07 15:49:15.42hr 52min ago            28.58               N
26  2021-10-07 15:38:14.53hr 03min ago            37.55               N
27  2021-10-07 15:25:04.23hr 17min ago            37.69               N
28  2021-10-07 15:24:38.03hr 17min ago            31.58               N
29  2021-10-07 15:23:14.03hr 18min ago            28.57               N
30  2021-10-07 15:07:25.03hr 34min ago            19.84               S
31  2021-10-07 14:54:14.33hr 47min ago            37.39               N
32  2021-10-07 14:51:46.23hr 50min ago            19.14               N
33  2021-10-07 14:49:38.23hr 52min ago            19.16               N
34  2021-10-07 14:37:30.04hr 04min ago            10.67               N
35  2021-10-07 14:26:04.74hr 16min ago            28.58               N
36  2021-10-07 14:24:30.04hr 17min ago            41.30               N
37  2021-10-07 14:12:20.64hr 29min ago            40.44               N
38  2021-10-07 14:10:47.04hr 31min ago            20.87               S
39  2021-10-07 14:02:47.34hr 39min ago            32.72               N
40  2021-10-07 14:02:09.14hr 39min ago            39.02               N
41  2021-10-07 13:52:50.64hr 49min ago            38.84               S
42  2021-10-07 13:47:00.14hr 55min ago            62.39               N
43  2021-10-07 13:44:12.04hr 57min ago             5.08               N
44  2021-10-07 13:41:24.25hr 00min ago            35.52               N
45  2021-10-07 13:24:32.95hr 17min ago            28.55               N
46  2021-10-07 13:18:26.35hr 23min ago            28.56               N
47  2021-10-07 13:16:23.55hr 25min ago            44.28               N
48  2021-10-07 13:14:20.85hr 27min ago            28.57               N
49  2021-10-07 13:13:38.65hr 28min ago            33.58               S
50                                 NaN              NaN             NaN
51                       12345678910»    12345678910»   12345678910»
52                                 NaN              NaN             NaN

   Longitude degrees                       Depth km        Mag [+]  \
       12345678910» 12345678910».1  12345678910»  12345678910»
0             118.33               W              1             Md
1              94.81               E            107             mb
2              17.84               W             12             ML
3             120.79               E            158             Mw
4              26.39               W             10             mb
5              16.10               W             16             ML
6              60.29               W              2             ML
7             106.89               E             10              M
8             130.21               E            151              M
9              26.21               E              7             ML
10             17.85               W             11             ML
11             12.22               E             10             ML
12             17.82               W             14             ML
13            129.59               E             10              M
14             25.30               E              8             ML
15             17.84               W             10             ML
16             17.85               W             13             ML
17            137.93               E            378             mb
18             86.33               W             26              M
19            155.50               W             35             ML
20             72.93               W              7              M
21             17.84               W             14             ML
22             17.85               W             13             ML
23             88.35               W             43             mb
24             17.84               W             12             ML
25             17.84               W             10             ML
26             44.73               E              6             ML
27             30.15               E              5             ML
28            104.55               W              5             ML
29             17.83               W             10             ML
30             71.08               W             29              M
31            117.11               W              0             ml
32            155.38               W             30             Ml
33            155.48               W             32             Ml
34             86.58               W             13              M
35             17.83               W             37             ML
36            142.20               E             60              M
37             51.78               E             62             ML
38             69.10               W            111              M
39            100.70               W              7             ML
40             27.86               E              7             ML
41            175.18               E            331              M
42            150.61               W             68             ML
43            126.15               E             32              M
44            140.07               E             60             Mw
45             17.85               W             14             ML
46             17.83               W             11             ML
47             92.67               E              2             mb
48             17.83               W             11             ML
49            138.68               E              2             ML
50               NaN             NaN            NaN            NaN
51     12345678910»   12345678910»  12345678910»  12345678910»
52               NaN             NaN            NaN            NaN

   Region name [+]                   Last update [-] Unnamed: 12_level_0
     12345678910»                     12345678910»       12345678910»
0              2.3                CENTRAL CALIFORNIA    2021-10-07 18:37
1              5.6                           MYANMAR    2021-10-07 18:40
2              2.7      CANARY ISLANDS, SPAIN REGION    2021-10-07 18:29
3              5.2              MINDORO, PHILIPPINES    2021-10-07 18:40
4              5.5     SOUTH SANDWICH ISLANDS REGION    2021-10-07 18:38
5              1.9      CANARY ISLANDS, SPAIN REGION    2021-10-07 18:03
6              4.4   GUADELOUPE REGION, LEEWARD ISL.    2021-10-07 18:15
7              2.5                   JAVA, INDONESIA    2021-10-07 18:10
8              4.5                         BANDA SEA    2021-10-07 17:50
9              2.1  NEAR THE COAST OF WESTERN TURKEY    2021-10-07 17:39
10             2.5      CANARY ISLANDS, SPAIN REGION    2021-10-07 17:34
11             2.7                    NORTHERN ITALY    2021-10-07 17:54
12             3.5      CANARY ISLANDS, SPAIN REGION    2021-10-07 17:34
13             3.0                  SERAM, INDONESIA    2021-10-07 17:35
14             3.0                     CRETE, GREECE    2021-10-07 17:02
15             3.4      CANARY ISLANDS, SPAIN REGION    2021-10-07 17:06
16             2.6      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:58
17             4.1         IZU ISLANDS, JAPAN REGION    2021-10-07 17:44
18             2.9           OFF COAST OF COSTA RICA    2021-10-07 16:36
19             2.8          ISLAND OF HAWAII, HAWAII    2021-10-07 16:35
20             2.5                      AISEN, CHILE    2021-10-07 16:36
21             2.7      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:47
22             2.9      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:46
23             4.0              OFFSHORE EL SALVADOR    2021-10-07 16:49
24             3.1      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:01
25             3.6      CANARY ISLANDS, SPAIN REGION    2021-10-07 16:40
26             2.7    TURKEY-IRAN-IRAQ BORDER REGION    2021-10-07 16:00
27             2.5                    WESTERN TURKEY    2021-10-07 15:44
28             2.5                     WESTERN TEXAS    2021-10-07 17:19
29             2.7      CANARY ISLANDS, SPAIN REGION    2021-10-07 15:41
30             2.7      OFF COAST OF TARAPACA, CHILE    2021-10-07 15:24
31             2.3                            NEVADA    2021-10-07 16:09
32             2.1          ISLAND OF HAWAII, HAWAII    2021-10-07 14:57
33             2.4          ISLAND OF HAWAII, HAWAII    2021-10-07 14:55
34             4.5           OFF COAST OF COSTA RICA    2021-10-07 15:21
35             3.8      CANARY ISLANDS, SPAIN REGION    2021-10-07 15:08
36             4.1            HOKKAIDO, JAPAN REGION    2021-10-07 14:35
37             3.2  CASPIAN SEA, OFFSHR TURKMENISTAN    2021-10-07 15:32
38             2.8                   TARAPACA, CHILE    2021-10-07 14:52
39             2.2                     WESTERN TEXAS    2021-10-07 18:36
40             2.1                    WESTERN TURKEY    2021-10-07 14:26
41             3.1       NORTH ISLAND OF NEW ZEALAND    2021-10-07 14:00
42             3.2                    CENTRAL ALASKA    2021-10-07 16:25
43             3.2             MINDANAO, PHILIPPINES    2021-10-07 13:56
44             5.9  NEAR EAST COAST OF HONSHU, JAPAN    2021-10-07 14:53
45             3.2      CANARY ISLANDS, SPAIN REGION    2021-10-07 13:30
46             2.8      CANARY ISLANDS, SPAIN REGION    2021-10-07 13:35
47             4.6          NORTHERN XINJIANG, CHINA    2021-10-07 16:06
48             2.7      CANARY ISLANDS, SPAIN REGION    2021-10-07 13:36
49             2.1     NEAR COAST OF SOUTH AUSTRALIA    2021-10-07 14:08
50             NaN                               NaN                 NaN
51   12345678910»                     12345678910»       12345678910»
52             NaN                               NaN                 NaN

In [19]:
df_eq = df_eq.iloc[0:50, 3:12]

In [20]:
df_eq.columns

MultiIndex([(  'Date & Time UTC',   '12345678910»'),
            ( 'Latitude degrees',   '12345678910»'),
            ( 'Latitude degrees', '12345678910».1'),
            ('Longitude degrees',   '12345678910»'),
            ('Longitude degrees', '12345678910».1'),
            (         'Depth km',   '12345678910»'),
            (          'Mag [+]',   '12345678910»'),
            (  'Region name [+]',   '12345678910»'),
            (  'Last update [-]',   '12345678910»')],
           )

In [21]:
df_eq.columns = [x[0].replace(' [+]','').replace(' [-]','') for x in df_eq.columns]
df_eq.head(1)

,Date & Time UTC,Latitude degrees,Latitude degrees,Longitude degrees,Longitude degrees,Depth km,Mag,Region name,Last update
0,2021-10-07 18:36:07.106min ago,37.00,N,118.33,W,1,Md,2.3,CENTRAL CALIFORNIA

In [22]:
df_eq = df_eq.drop(columns=['Mag'])
df_eq.head(1)

,Date & Time UTC,Latitude degrees,Latitude degrees,Longitude degrees,Longitude degrees,Depth km,Region name,Last update
0,2021-10-07 18:36:07.106min ago,37.00,N,118.33,W,1,2.3,CENTRAL CALIFORNIA

In [23]:
df_eq.columns = ['Date & Time UTC', 'Latitude', 'Latitude N-S', 'Longitude', 'Longitude E-W', 'Depth Km', 'Magnitude', 'Region name']
df_eq.head(1)

,Date & Time UTC,Latitude,Latitude N-S,Longitude,Longitude E-W,Depth Km,Magnitude,Region name
0,2021-10-07 18:36:07.106min ago,37.00,N,118.33,W,1,2.3,CENTRAL CALIFORNIA

In [24]:
df_eq['Date & Time UTC'] = df_eq['Date & Time UTC'].apply(lambda x : str(x)[:19])
df_eq.head(1)

,Date & Time UTC,Latitude,Latitude N-S,Longitude,Longitude E-W,Depth Km,Magnitude,Region name
0,2021-10-07 18:36:07,37.00,N,118.33,W,1,2.3,CENTRAL CALIFORNIA

In [25]:
df_eq['Date'] = pd.to_datetime(df_eq['Date & Time UTC']).dt.date
df_eq['Time'] = pd.to_datetime(df_eq['Date & Time UTC']).dt.time
df_eq.head(1)

,Date & Time UTC,Latitude,Latitude N-S,Longitude,Longitude E-W,Depth Km,Magnitude,Region name,Date,Time
0,2021-10-07 18:36:07,37.00,N,118.33,W,1,2.3,CENTRAL CALIFORNIA,2021-10-07,18:36:07

In [26]:
df_eq = df_eq.iloc[:, 1:12]
df_eq = df_eq[['Date', 'Time', 'Latitude', 'Latitude N-S', 'Longitude', 'Longitude E-W', 'Depth Km', 'Magnitude', 'Region name']]
df_eq

,Date,Time,Latitude,Latitude N-S,Longitude,Longitude E-W,Depth Km,Magnitude,Region name
0,2021-10-07,18:36:07,37.00,N,118.33,W,1,2.3,CENTRAL CALIFORNIA
1,2021-10-07,18:28:03,22.36,N,94.81,E,107,5.6,MYANMAR
2,2021-10-07,18:24:31,28.56,N,17.84,W,12,2.7,"CANARY ISLANDS, SPAIN REGION"
3,2021-10-07,18:14:53,13.86,N,120.79,E,158,5.2,"MINDORO, PHILIPPINES"
4,2021-10-07,17:56:14,55.70,S,26.39,W,10,5.5,SOUTH SANDWICH ISLANDS REGION
5,2021-10-07,17:55:09,28.38,N,16.10,W,16,1.9,"CANARY ISLANDS, SPAIN REGION"
6,2021-10-07,17:53:23,16.90,N,60.29,W,2,4.4,"GUADELOUPE REGION, LEEWARD ISL."
7,2021-10-07,17:45:21,7.92,S,106.89,E,10,2.5,"JAVA, INDONESIA"
8,2021-10-07,17:43:01,6.47,S,130.21,E,151,4.5,BANDA SEA
9,2021-10-07,17:24:24,39.53,N,26.21,E,7,2.1,NEAR THE COAST OF WESTERN TURKEY
10,2021-10-07,17:21:50,28.56,N,17.85,W,11,2.5,"CANARY ISLANDS, SPAIN REGION"
11,2021-10-07,17:17:46,44.20,N,12.22,E,10,2.7,NORTHERN ITALY
12,2021-10-07,17:14:38,28.56,N,17.82,W,14,3.5,"CANARY ISLANDS, SPAIN REGION"
13,2021-10-07,17:02:39,2.76,S,129.59,E,10,3.0,"SERAM, INDONESIA"
14,2021-10-07,16:59:48,35.19,N,25.30,E,8,3.0,"CRETE, GREECE"
15,2021-10-07,16:52:59,28.56,N,17.84,W,10,3.4,"CANARY ISLANDS, SPAIN REGION"
16,2021-10-07,16:47:20,28.56,N,17.85,W,13,2.6,"CANARY ISLANDS, SPAIN REGION"
17,2021-10-07,16:44:22,31.84,N,137.93,E,378,4.1,"IZU ISLANDS, JAPAN REGION"
18,2021-10-07,16:32:21,10.98,N,86.33,W,26,2.9,OFF COAST OF COSTA RICA
19,2021-10-07,16:25:17,19.24,N,155.50,W,35,2.8,"ISLAND OF HAWAII, HAWAII"
20,2021-10-07,16:24:06,45.88,S,72.93,W,7,2.5,"AISEN, CHILE"
21,2021-10-07,16:19:28,28.57,N,17.84,W,14,2.7,"CANARY ISLANDS, SPAIN REGION"
22,2021-10-07,16:13:42,28.56,N,17.85,W,13,2.9,"CANARY ISLANDS, SPAIN REGION"
23,2021-10-07,16:11:43,12.67,N,88.35,W,43,4.0,OFFSHORE EL SALVADOR
24,2021-10-07,15:52:54,28.56,N,17.84,W,12,3.1,"CANARY ISLANDS, SPAIN REGION"
25,2021-10-07,15:49:15,28.58,N,17.84,W,10,3.6,"CANARY ISLANDS, SPAIN REGION"
26,2021-10-07,15:38:14,37.55,N,44.73,E,6,2.7,TURKEY-IRAN-IRAQ BORDER REGION
27,2021-10-07,15:25:04,37.69,N,30.15,E,5,2.5,WESTERN TURKEY
28,2021-10-07,15:24:38,31.58,N,104.55,W,5,2.5,WESTERN TEXAS
29,2021-10-07,15:23:14,28.57,N,17.83,W,10,2.7,"CANARY ISLANDS, SPAIN REGION"
30,2021-10-07,15:07:25,19.84,S,71.08,W,29,2.7,"OFF COAST OF TARAPACA, CHILE"
31,2021-10-07,14:54:14,37.39,N,117.11,W,0,2.3,NEVADA
32,2021-10-07,14:51:46,19.14,N,155.38,W,30,2.1,"ISLAND OF HAWAII, HAWAII"
33,2021-10-07,14:49:38,19.16,N,155.48,W,32,2.4,"ISLAND OF HAWAII, HAWAII"
34,2021-10-07,14:37:30,10.67,N,86.58,W,13,4.5,OFF COAST OF COSTA RICA
35,2021-10-07,14:26:04,28.58,N,17.83,W,37,3.8,"CANARY ISLANDS, SPAIN REGION"
36,2021-10-07,14:24:30,41.30,N,142.20,E,60,4.1,"HOKKAIDO, JAPAN REGION"
37,2021-10-07,14:12:20,40.44,N,51.78,E,62,3.2,"CASPIAN SEA, OFFSHR TURKMENISTAN"
38,2021-10-07,14:10:47,20.87,S,69.10,W,111,2.8,"TARAPACA, CHILE"
39,2021-10-07,14:02:47,32.72,N,100.70,W,7,2.2,WESTERN TEXAS
40,2021-10-07,14:02:09,39.02,N,27.86,E,7,2.1,WESTERN TURKEY
41,2021-10-07,13:52:50,38.84,S,175.18,E,331,3.1,NORTH ISLAND OF NEW ZEALAND
42,2021-10-07,13:47:00,62.39,N,150.61,W,68,3.2,CENTRAL ALASKA
43,2021-10-07,13:44:12,5.08,N,126.15,E,32,3.2,"MINDANAO, PHILIPPINES"
44,2021-10-07,13:41:24,35.52,N,140.07,E,60,5.9,"NEAR EAST COAST OF HONSHU, JAPAN"
45,2021-10-07,13:24:32,28.55,N,17.85,W,14,3.2,"CANARY ISLANDS, SPAIN REGION"
46,2021-10-07,13:18:26,28.56,N,17.83,W,11,2.8,"CANARY ISLANDS, SPAIN REGION"
47,2021-10-07,13:16:23,44.28,N,92.67,E,2,4.6,"NORTHERN XINJIANG, CHINA"
48,2021-10-07,13:14:20,28.57,N,17.83,W,11,2.7,"CANARY ISLANDS, SPAIN REGION"
49,2021-10-07,13:13:38,33.58,S,138.68,E,2,2.1,NEAR COAST OF SOUTH AUSTRALIA

## Bonus
- Find the IMDB's Top 250 data.
- You should have movie name, year release, director name and actors.
- Create a dataframe with the data you collected.
- Use the url below to this exercise.
```python
url_imdb = 'https://www.imdb.com/chart/top'
```

In [27]:
# Your code here

url_imdb = 'https://www.imdb.com/chart/top'

In [28]:
get_html = requests.get(url_imdb)
get_html

In [29]:
html_content = get_html.content

In [30]:
soup = BeautifulSoup(html_content, "lxml")

In [31]:
movies = soup.find_all('td', {'class':'titleColumn'})
movies[0]

<td class="titleColumn">
      1.
      <a href="/title/tt0111161/" title="Frank Darabont (dir.), Tim Robbins, Morgan Freeman">Um Sonho de Liberdade</a>
<span class="secondaryInfo">(1994)</span>
</td>

In [32]:
titles = [movie.find('a').text for movie in movies]
titles[0]

'Um Sonho de Liberdade'

In [33]:
years = [movie.find('span').text[1:-1] for movie in movies]
years[0]

'1994'

In [34]:
directors = [movie.find('a').get('title').split(',')[0][:-7] for movie in movies]
directors[0]

'Frank Darabont'

In [35]:
actors = [','.join(movie.find('a').get('title').split(',')[1:]) for movie in movies]
actors[0]

' Tim Robbins, Morgan Freeman'

In [36]:
movies_dict = {'Title': titles, 'Release': years, 'Director': directors, 'Actors': actors}

movies_df = pd.DataFrame(movies_dict)
movies_df

,Title,Release,Director,Actors
0,Um Sonho de Liberdade,1994,Frank Darabont,"Tim Robbins, Morgan Freeman"
1,O Poderoso Chefão,1972,Francis Ford Coppola,"Marlon Brando, Al Pacino"
2,O Poderoso Chefão II,1974,Francis Ford Coppola,"Al Pacino, Robert De Niro"
3,Batman: O Cavaleiro das Trevas,2008,Christopher Nolan,"Christian Bale, Heath Ledger"
4,12 Homens e uma Sentença,1957,Sidney Lumet,"Henry Fonda, Lee J. Cobb"
...,...,...,...,...
245,"Paris, Texas",1984,Wim Wenders,"Harry Dean Stanton, Nastassja Kinski"
246,A Princesa Prometida,1987,Rob Reiner,"Cary Elwes, Mandy Patinkin"
247,Noites de Cabíria,1957,Federico Fellini,"Giulietta Masina, François Périer"
248,Rififi,1955,Jules Dassin,"Jean Servais, Carl Möhner"
249,Ratsasan,2018,Ram Kumar,"Vishnu Vishal, Amala Paul"